on:
  workflow_call:
    inputs:
      native:
        type: boolean
        description: 'Whether to run the native OS/ARCH build (true/false)'
        required: false
        default: true
      snapshot:
        type: boolean
        description: 'Whether to run the snapshot (all release OS/Arch combos) build (true/false)'
        required: false
        default: false

jobs:
  native:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ inputs.native }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/setup
      - run: go mod download
      - run: go build -v ./...

  snapshot:
    name: Snapshot Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ inputs.snapshot }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ./.github/actions/setup
      - name: Cache Go modules and build cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-goreleaser-snapshot-go-${{ hashFiles('**/go.sum') }}
      - name: Test snapshot build
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7.0.0
        with:
          version: latest
          args: release --snapshot --clean --skip sign
